using UnityEngine;
using UnityEngine.InputSystem;

public class TouchToggle : MonoBehaviour
{
    private Camera cam;

    public LevelManager levelManager;

    [SerializeField] private GameObject ToggleObject;

    void Start()
    {
        //Reference main camera upon start up (I think for the raycast thing)
        cam = Camera.main;
    }

    void Update()
    {
        //If there is a touchscreen and the button is currently being pressed
        if (Touchscreen.current != null && Touchscreen.current.primaryTouch.press.wasPressedThisFrame)
        {
            CheckTap(Touchscreen.current.primaryTouch.position.ReadValue());
        }
        //Else if, there is a mouse and left mouse button is being pressed
        else if (Mouse.current != null && Mouse.current.leftButton.wasPressedThisFrame)
        {
            CheckTap(Mouse.current.position.ReadValue());
        }
    }

    void CheckTap(Vector2 screenPos)
    {
        //Gets the screen position generated by Checktap(), converts it into world space, then stores it in a local var named worldPos
        Vector2 worldPos = cam.ScreenToWorldPoint(screenPos);

        //Creates a raycast thing named hit, which is shot from the worldPos and has a direction of Vector2.zero (which means it will only check for collisions at that point)
        RaycastHit2D hit = Physics2D.Raycast(worldPos, Vector2.zero);

        //If the raycast hit something and the thing it hit is the game object
        if (hit.collider != null && hit.collider.gameObject == gameObject)
        {
            Debug.Log("Hit");
            //GetComponent<InputObject>().PlaySound();

            if (levelManager.playerInputAllowed)
            {
                levelManager.AddInput(GetComponent<InputObject>().inputType);
                GetComponent<InputObject>().Animate();
                GetComponent<InputObject>().PlaySound();
            }

        }
    }
}